"""Storage interfaces for swappable local/PostgreSQL implementations."""

from __future__ import annotations

from pathlib import Path
from typing import Protocol

from grna.storage.models import ArtifactMetadata, JobRecord


class JobStore(Protocol):
    """Persistence interface for scan job status."""

    def save(self, job: JobRecord) -> JobRecord:
        """Persist a job record."""

    def get(self, job_id: str) -> JobRecord:
        """Return a job record by ID."""


class ArtifactStore(Protocol):
    """Persistence interface for generated artifacts."""

    def job_artifact_dir(self, job_id: str) -> Path:
        """Return the root-bound artifact directory for a job."""

    def save_artifact(
        self,
        job_id: str,
        relative_path: str,
        content: bytes,
        artifact_type: str,
        content_type: str | None = None,
    ) -> ArtifactMetadata:
        """Persist artifact content and return metadata."""

    def list_artifacts(self, job_id: str) -> list[ArtifactMetadata]:
        """List metadata for artifacts generated by a job."""

