"""Markdown release-note rendering."""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

from grna.diagrams.mermaid import MermaidDiagramSet
from grna.evidence.aggregator import AnalyticsBundle
from grna.evidence.models import EvidenceIndex


@dataclass(frozen=True, slots=True)
class ReleaseNoteContent:
    """Input model for Markdown release-note rendering."""

    title: str
    release_name: str
    repository: str
    generated_at: str
    analytics: AnalyticsBundle
    diagrams: MermaidDiagramSet
    evidence: EvidenceIndex | None = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize to JSON-compatible data."""

        return asdict(self)


class MarkdownReleaseNoteRenderer:
    """Render evidence-backed release-note Markdown."""

    def render(self, content: ReleaseNoteContent) -> str:
        """Render Markdown for a completed analytics bundle."""

        lines = [
            f"# {content.title}",
            "",
            "## Document Control",
            "",
            f"- Release: {content.release_name}",
            f"- Repository: {content.repository}",
            f"- Generated At: {content.generated_at}",
            f"- Job ID: {content.analytics.job_id}",
            "",
            "## Executive Summary",
            "",
            _project_intent(content.analytics),
            "",
            "## Release Overview",
            "",
            _missing_or(
                "Analytics bundle generated for repository review.",
                content.analytics.gaps,
            ),
            "",
            "## Repository Overview",
            "",
            _section_summary(content.analytics, "inventory"),
            "",
            "## Project Intent",
            "",
            _project_intent(content.analytics),
            "",
            "## Technology Inventory",
            "",
            _technology_table(content.analytics),
            "",
            "## Architecture Overview",
            "",
            *_diagram_blocks(content.diagrams),
            "",
            "## Interface Inventory",
            "",
            _interface_summary(content.analytics),
            "",
            "## Code Analytics",
            "",
            _section_summary(content.analytics, "code_structure"),
            "",
            "## Test Analytics",
            "",
            _test_summary(content.analytics),
            "",
            "## Coverage Analytics",
            "",
            _coverage_summary(content.analytics),
            "",
            "## Commit Analytics",
            "",
            _commit_summary(content.analytics),
            "",
            "## Quality and Risk Assessment",
            "",
            _risk_summary(content.analytics),
            "",
            "## Known Gaps",
            "",
            _gaps(content.analytics, content.diagrams),
            "",
            "## Evidence Traceability",
            "",
            _evidence_appendix(content),
            "",
            "## Appendix",
            "",
            "Generated by BOS Genesis Release Note Agent.",
            "",
        ]
        return "\n".join(lines)


def _project_intent(bundle: AnalyticsBundle) -> str:
    section = bundle.sections.get("documentation")
    if not section:
        return "Project intent is not available because documentation analysis is missing."
    intent = section.data.get("project_intent", {})
    text = intent.get("text")
    source = intent.get("source", "unavailable")
    evidence = intent.get("evidence_id")
    if not text:
        return "Project intent is unavailable from current evidence."
    suffix = f" Evidence: `{evidence}`." if evidence else ""
    return f"{text} Intent source: `{source}`.{suffix}"


def _section_summary(bundle: AnalyticsBundle, section_name: str) -> str:
    section = bundle.sections.get(section_name)
    if not section:
        return f"{section_name.replace('_', ' ').title()} evidence is not available."
    if section.gaps:
        return _missing_or("Section data is available with gaps.", section.gaps)
    evidence_count = len(section.evidence_ids)
    return f"Section `{section_name}` is available with {evidence_count} evidence references."


def _technology_table(bundle: AnalyticsBundle) -> str:
    section = bundle.sections.get("technology")
    if not section:
        return "Technology inventory is not available."
    findings = section.data.get("findings", [])
    if not findings:
        return _missing_or("No technology findings were detected.", section.gaps)
    lines = ["| Technology | Category | Confidence | Evidence |", "| --- | --- | ---: | --- |"]
    for finding in findings:
        evidence = ", ".join(f"`{item}`" for item in finding.get("evidence_ids", [])[:3])
        lines.append(
            "| {name} | {category} | {confidence:.2f} | {evidence} |".format(
                name=finding.get("name", "Unknown"),
                category=finding.get("category", "unknown"),
                confidence=float(finding.get("confidence", 0.0)),
                evidence=evidence or "Not available",
            )
        )
    return "\n".join(lines)


def _interface_summary(bundle: AnalyticsBundle) -> str:
    section = bundle.sections.get("interfaces")
    if not section:
        return "Interface inventory is not available."
    interfaces = section.data.get("interfaces", [])
    recommendations = section.data.get("recommendations", [])
    lines = [f"Detected interfaces: {len(interfaces)}."]
    if recommendations:
        lines.append("Recommendations: " + "; ".join(recommendations))
    return "\n".join(lines)


def _test_summary(bundle: AnalyticsBundle) -> str:
    section = bundle.sections.get("test_coverage")
    if not section:
        return "Test evidence is not available."
    data = section.data
    return (
        f"Test source files: {len(data.get('test_sources', []))}. "
        f"Parsed test reports: {len(data.get('test_reports', []))}."
    )


def _coverage_summary(bundle: AnalyticsBundle) -> str:
    section = bundle.sections.get("test_coverage")
    if not section:
        return "Coverage evidence is not available."
    reports = section.data.get("coverage_reports", [])
    if not reports:
        return "Coverage evidence is missing; no coverage percentage is reported."
    lines = ["| Report | Type | Line Rate | Evidence |", "| --- | --- | ---: | --- |"]
    for report in reports:
        rate = report.get("line_rate")
        rate_text = "Not available" if rate is None else f"{float(rate) * 100:.1f}%"
        lines.append(
            "| {path} | {kind} | {rate} | `{evidence}` |".format(
                path=report.get("path", "unknown"),
                kind=report.get("report_type", "unknown"),
                rate=rate_text,
                evidence=report.get("evidence_id") or "not available",
            )
        )
    return "\n".join(lines)


def _commit_summary(bundle: AnalyticsBundle) -> str:
    section = bundle.sections.get("commits")
    if not section:
        return "Commit analytics are not available."
    data = section.data
    return (
        f"Commits analyzed: {data.get('commit_count', 0)}. "
        f"Authors: {len(data.get('authors', []))}. "
        f"Changed files: {len(data.get('changed_files', []))}."
    )


def _risk_summary(bundle: AnalyticsBundle) -> str:
    section = bundle.sections.get("commits")
    if not section:
        return "Risk assessment is limited because commit analytics are unavailable."
    risky = section.data.get("risky_areas", [])
    if not risky:
        return "No high-risk changed areas were detected from current evidence."
    return "Risky areas: " + ", ".join(item.get("path", "unknown") for item in risky[:10])


def _diagram_blocks(diagrams: MermaidDiagramSet) -> list[str]:
    lines: list[str] = []
    for diagram in diagrams.diagrams:
        lines.extend(
            [
                f"### {diagram.title}",
                "",
                f"{diagram.caption} Confidence: `{diagram.confidence:.2f}`.",
                "",
                "```mermaid",
                diagram.source,
                "```",
                "",
            ]
        )
    if diagrams.gaps:
        lines.append("Diagram gaps: " + "; ".join(diagrams.gaps))
    return lines or ["No diagrams are available from current evidence."]


def _gaps(bundle: AnalyticsBundle, diagrams: MermaidDiagramSet) -> str:
    gaps = [*bundle.gaps, *diagrams.gaps]
    if not gaps:
        return "No known evidence gaps were detected."
    return "\n".join(f"- {gap}" for gap in sorted(set(gaps)))


def _evidence_appendix(content: ReleaseNoteContent) -> str:
    if not content.analytics.evidence_ids:
        return "No evidence references are available."
    lines = ["| Evidence ID | Source | Summary |", "| --- | --- | --- |"]
    for evidence_id in content.analytics.evidence_ids:
        record = content.evidence.get(evidence_id) if content.evidence else None
        source = record.source_path if record else "Not available"
        summary = record.summary if record else "Evidence metadata not available."
        lines.append(f"| `{evidence_id}` | {source} | {summary} |")
    return "\n".join(lines)


def _missing_or(prefix: str, gaps: tuple[str, ...] | list[str]) -> str:
    if not gaps:
        return prefix
    return prefix + " Missing evidence: " + "; ".join(gaps)
